In [1]:
%pip install pyannote.audio
%pip install numpy==1.26

Collecting pyannote.audio
  Downloading pyannote_audio-4.0.4-py3-none-any.whl.metadata (13 kB)
Collecting asteroid-filterbanks>=0.4.0 (from pyannote.audio)
  Downloading asteroid_filterbanks-0.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting einops>=0.8.1 (from pyannote.audio)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: huggingface-hub>=0.28.1 in .\venv312\lib\site-packages (from pyannote.audio) (0.36.2)
Collecting lightning>=2.4 (from pyannote.audio)
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
Collecting matplotlib>=3.10.0 (from pyannote.audio)
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting opentelemetry-api>=1.34.0 (from pyannote.audio)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp>=1.34.0 (from pyannote.audio)
  Downloading opentelemetry_exporter_otlp-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.34.0 (from pyannote.audio)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting pyannote-core>=6.0.1 (from pyannote.audio)
  Downloading pyannote_core-6.0.1-py3-none-any.whl.metadata (1.9 kB)
Collecting pyannote-database>=6.1.1 (from pyannote.audio)
  Downloading pyannote_database-6.1.1-py3-none-any.whl.metadata (30 kB)
Collecting pyannote-metrics>=4.0.0 (from pyannote.audio)
  Downloading pyannote_metrics-4.0.0-py3-none-any.whl.metadata (2.2 kB)
Collecting pyannote-pipeline>=4.0.0 (from pyannote.audio)
  Downloading pyannote_pipeline-4.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting pyannoteai-sdk>=0.3.0 (from pyannote.audio)
  Downloading pyannoteai_sdk-0.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting pytorch-metric-learning>=2.8.1 (from pyannote.audio)
  Downloading pytorch_metric_learning-2.9.0-py3-none-any.whl.metadata (18 kB)
Collecting rich>=13.9.4 (from pyannote.audio)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: safetensors>=0.5.2 in .\venv312\lib\site-packages (from pyannote.audio) (0.7.0)
Collecting torch-audiomentations>=0.12.0 (from pyannote.audio)
  Downloading torch_audiomentations-0.12.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=2.8.0 in .\venv312\lib\site-packages (from pyannote.audio) (2.10.0)
Collecting torchaudio>=2.8.0 (from pyannote.audio)
  Downloading torchaudio-2.10.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torchcodec>=0.7.0 in .\venv312\lib\site-packages (from pyannote.audio) (0.10.0)
Collecting torchmetrics>=1.6.1 (from pyannote.audio)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy in .\venv312\lib\site-packages (from asteroid-filterbanks>=0.4.0->pyannote.audio) (2.4.3)
Requirement already satisfied: typing-extensions in .\venv312\lib\site-packages (from asteroid-filterbanks>=0.4.0->pyannote.audio) (4.15.0)
Requirement already satisfied: filelock in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (26.0)
Requirement already satisfied: pyyaml>=5.1 in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (6.0.3)
Requirement already satisfied: requests in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in .\venv312\lib\site-packages (from huggingface-hub>=0.28.1->pyannote.audio) (4.67.3)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning>=2.4->pyannote.audio)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning>=2.4->pyannote.audio)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.0->pyannote.audio)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.10.0->pyannote.audio)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.10.0->pyannote.audio)
  Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.10.0->pyannote.audio)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Collecting pillow>=8 (from matplotlib>=3.10.0->pyannote.audio)
  Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib>=3.10.0->pyannote.audio)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in .\venv312\lib\site-packages (from matplotlib>=3.10.0->pyannote.audio) (2.9.0.post0)
Collecting importlib-metadata<8.8.0,>=6.0 (from opentelemetry-api>=1.34.0->pyannote.audio)
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc==1.40.0 (from opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl.metadata (2.6 kB)
Collecting opentelemetry-exporter-otlp-proto-http==1.40.0 (from opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading opentelemetry_exporter_otlp_proto_http-1.40.0-py3-none-any.whl.metadata (2.5 kB)
Collecting googleapis-common-protos~=1.57 (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Using cached googleapis_common_protos-1.73.0-py3-none-any.whl.metadata (9.4 kB)
Collecting grpcio<2.0.0,>=1.63.2 (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading grpcio-1.78.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting protobuf<7.0,>=5.0 (from opentelemetry-proto==1.40.0->opentelemetry-exporter-otlp-proto-grpc==1.40.0->opentelemetry-exporter-otlp>=1.34.0->pyannote.audio)
  Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk>=1.34.0->pyannote.audio)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pandas>=2.2.3 in .\venv312\lib\site-packages (from pyannote-core>=6.0.1->pyannote.audio) (3.0.1)
Collecting sortedcontainers>=2.4.0 (from pyannote-core>=6.0.1->pyannote.audio)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting scikit-learn>=1.6.1 (from pyannote-metrics>=4.0.0->pyannote.audio)
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting scipy>=1.15.1 (from pyannote-metrics>=4.0.0->pyannote.audio)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting optuna>=4.2.0 (from pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.9.4->pyannote.audio)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv312\lib\site-packages (from rich>=13.9.4->pyannote.audio) (2.19.2)
Requirement already satisfied: sympy>=1.13.3 in .\venv312\lib\site-packages (from torch>=2.8.0->pyannote.audio) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\venv312\lib\site-packages (from torch>=2.8.0->pyannote.audio) (3.6.1)
Requirement already satisfied: jinja2 in .\venv312\lib\site-packages (from torch>=2.8.0->pyannote.audio) (3.1.6)
Requirement already satisfied: setuptools in .\venv312\lib\site-packages (from torch>=2.8.0->pyannote.audio) (82.0.1)
Collecting julius<0.3,>=0.2.3 (from torch-audiomentations>=0.12.0->pyannote.audio)
  Downloading julius-0.2.7.tar.gz (59 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting torch-pitch-shift>=1.2.2 (from torch-audiomentations>=0.12.0->pyannote.audio)
  Downloading torch_pitch_shift-1.2.5-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\venv312\lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (3.13.3)
Collecting zipp>=3.20 (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.34.0->pyannote.audio)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.9.4->pyannote.audio)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting alembic>=1.5.0 (from optuna>=4.2.0->pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna>=4.2.0->pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Collecting sqlalchemy>=1.4.2 (from optuna>=4.2.0->pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: tzdata in .\venv312\lib\site-packages (from pandas>=2.2.3->pyannote-core>=6.0.1->pyannote.audio) (2025.3)
Requirement already satisfied: six>=1.5 in .\venv312\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.0->pyannote.audio) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv312\lib\site-packages (from requests->huggingface-hub>=0.28.1->pyannote.audio) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in .\venv312\lib\site-packages (from requests->huggingface-hub>=0.28.1->pyannote.audio) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\venv312\lib\site-packages (from requests->huggingface-hub>=0.28.1->pyannote.audio) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in .\venv312\lib\site-packages (from requests->huggingface-hub>=0.28.1->pyannote.audio) (2026.2.25)
Collecting joblib>=1.3.0 (from scikit-learn>=1.6.1->pyannote-metrics>=4.0.0->pyannote.audio)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.6.1->pyannote-metrics>=4.0.0->pyannote.audio)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\venv312\lib\site-packages (from sympy>=1.13.3->torch>=2.8.0->pyannote.audio) (1.3.0)
Collecting primePy>=1.3 (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.12.0->pyannote.audio)
  Downloading primePy-1.3-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: colorama in .\venv312\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.28.1->pyannote.audio) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\venv312\lib\site-packages (from jinja2->torch>=2.8.0->pyannote.audio) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\venv312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.4->pyannote.audio) (1.23.0)
Collecting Mako (from alembic>=1.5.0->optuna>=4.2.0->pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote-pipeline>=4.0.0->pyannote.audio)
  Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Downloading pyannote_audio-4.0.4-py3-none-any.whl (893 kB)
   ---------------------------------------- 0.0/893.7 kB ? eta -:--:--
   --------------------------------------- 893.7/893.7 kB 39.5 MB/s eta 0:00:00
Downloading asteroid_filterbanks-0.4.0-py3-none-any.whl (29 kB)
Downloading einops-0.8.2-py3-none-any.whl (65 kB)
Downloading lightning-2.6.1-py3-none-any.whl (853 kB)
   ---------------------------------------- 0.0/853.6 kB ? eta -:--:--
   --------------------------------------- 853.6/853.6 kB 37.0 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------------------------- ---------- 6.0/8.1 MB 28.4 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 28.0 MB/s eta 0:00:00
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
Downloading opentelemetry_exporter_otlp-1.40.0-py3-none-any.whl (7.0 kB)
Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (20 kB)
Downloading opentelemetry_exporter_otlp_proto_http-1.40.0-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
Downloading pyannote_core-6.0.1-py3-none-any.whl (57 kB)
Downloading pyannote_database-6.1.1-py3-none-any.whl (53 kB)
Downloading pyannote_metrics-4.0.0-py3-none-any.whl (49 kB)
Downloading pyannote_pipeline-4.0.0-py3-none-any.whl (22 kB)
Downloading pyannoteai_sdk-0.4.0-py3-none-any.whl (8.9 kB)
Downloading pytorch_metric_learning-2.9.0-py3-none-any.whl (127 kB)
Using cached rich-14.3.3-py3-none-any.whl (310 kB)
Downloading torch_audiomentations-0.12.0-py3-none-any.whl (48 kB)
Downloading torchaudio-2.10.0-cp312-cp312-win_amd64.whl (475 kB)
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ---------------------------------------- 0.0/983.4 kB ? eta -:--:--
   --------------------------------------- 983.4/983.4 kB 45.1 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 32.8 MB/s eta 0:00:00
Downloading importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 39.4 MB/s eta 0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 8.0/8.0 MB 38.2 MB/s eta 0:00:00
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   --------- ------------------------------ 8.4/36.5 MB 43.5 MB/s eta 0:00:01
   --------- ------------------------------ 8.9/36.5 MB 21.3 MB/s eta 0:00:02
   ---------------- ----------------------- 15.5/36.5 MB 23.8 MB/s eta 0:00:01
   ---------------------------- ----------- 25.7/36.5 MB 29.6 MB/s eta 0:00:01
   ----------------------------------- ---- 32.5/36.5 MB 31.8 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 28.0 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 27.0 MB/s eta 0:00:00
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading torch_pitch_shift-1.2.5-py3-none-any.whl (5.0 kB)
Downloading pytorch_lightning-2.6.1-py3-none-any.whl (857 kB)
   ---------------------------------------- 0.0/857.3 kB ? eta -:--:--
   --------------------------------------- 857.3/857.3 kB 37.2 MB/s eta 0:00:00
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Using cached googleapis_common_protos-1.73.0-py3-none-any.whl (297 kB)
Downloading grpcio-1.78.0-cp312-cp312-win_amd64.whl (4.8 MB)
   ---------------------------------------- 0.0/4.8 MB ? eta -:--:--
   ---------------------------------------- 4.8/4.8 MB 36.3 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading primePy-1.3-py3-none-any.whl (4.0 kB)
Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 40.0 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl (231 kB)
Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Building wheels for collected packages: julius
  Building wheel for julius (pyproject.toml): started
  Building wheel for julius (pyproject.toml): finished with status 'done'
  Created wheel for julius: filename=julius-0.2.7-py3-none-any.whl size=22017 sha256=bc2b6dab364b24ab73c2d2934216cba497d9f41ec551a08d597bc1634381b3aa
  Stored in directory: c:\users\didgk\appdata\local\pip\cache\wheels\de\c1\ca\544dafe48401e8e2e17064dfe465a390fca9e8720ffa12e744
Successfully built julius

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting numpy==1.26
  Downloading numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ------------- -------------------------- 5.2/15.5 MB 26.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.4/15.5 MB 32.2 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 29.5 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\workspace\python\venv312\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\workspace\python\venv312\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
from dotenv import load_dotenv

load_dotenv()

HUGGING_FACE_TOKEN = os.getenv("HUGGING_FACE_TOKEN")

In [3]:
# instantiate the pipeline
from pyannote.audio import Pipeline

pipeline = Pipeline.from_pretrained(
  "pyannote/speaker-diarization-3.1",
  use_auth_token=HUGGING_FACE_TOKEN
)

c:\workspace\python\venv312\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\didgk\.cache\torch\pyannote\models--pyannote--speaker-diarization-3.1. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\workspace\python\venv312\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
c:\workspace\python\venv312\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
c:\workspace\python\venv312\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
c:\workspace\python\venv312\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
c:\workspace\python\venv312\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\didgk\.cache\torch\pyannote\models--pyannote--segmentation-3.0. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
c:\workspace\python\venv312\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\didgk\.cache\torch\pyannote\models--pyannote--wespeaker-voxceleb-resnet34-LM. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [4]:
import torch

# cuda가 사용 가능한 경우 cuda를 사용하도록 설정
if torch.cuda.is_available():
    pipeline.to(torch.device("cuda"))
    print('cuda is available')
else:
    print('cuda is not available')

cuda is not available

In [5]:
import soundfile as sf
import numpy as np

# MP3 → wav로 변환 후 넘기기
audio_path = r"C:\workspace\python\audio\싼기타_비싼기타.mp3"

# ffmpeg로 wav 변환
import subprocess
wav_path = audio_path.replace(".mp3", ".wav")
subprocess.run([
    "ffmpeg", "-i", audio_path, "-ar", "16000", "-ac", "1", wav_path, "-y"
])

# wav 파일로 실행
diarization = pipeline(wav_path)

# dump the diarization output to disk using RTTM format
with open("싼기타_비싼기타.rttm", "w", encoding='utf-8') as rttm:
    diarization.write_rttm(rttm)

c:\workspace\python\venv312\Lib\site-packages\pyannote\audio\models\blocks\pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ..\aten\src\ATen\native\ReduceOps.cpp:1760.)
  std = sequences.std(dim=-1, correction=1)

In [6]:
# RTTM을 CSV로 변환
import pandas as pd
rttm_path = "./싼기타_비싼기타.rttm"

df_rttm = pd.read_csv(
    rttm_path,      # rttm 파일 경로
    sep=' ',        # 구분자는 띄어쓰기
    header=None,    # 헤더는 없음
    names=['type', 'file', 'chnl', 'start', 'duration', 'C1', 'C2', 'speaker_id', 'C3', 'C4'] 
)

display(df_rttm)

       type      file  chnl    start  duration  C1  C2  speaker_id  C3  C4
0   SPEAKER  싼기타_비싼기타     1    0.976     5.823 NaN NaN  SPEAKER_01 NaN NaN
1   SPEAKER  싼기타_비싼기타     1    7.394     3.973 NaN NaN  SPEAKER_01 NaN NaN
2   SPEAKER  싼기타_비싼기타     1   11.757     4.907 NaN NaN  SPEAKER_01 NaN NaN
3   SPEAKER  싼기타_비싼기타     1   17.224    10.645 NaN NaN  SPEAKER_01 NaN NaN
4   SPEAKER  싼기타_비싼기타     1   28.667     1.528 NaN NaN  SPEAKER_01 NaN NaN
..      ...       ...   ...      ...       ...  ..  ..         ...  ..  ..
82  SPEAKER  싼기타_비싼기타     1  414.474     2.971 NaN NaN  SPEAKER_00 NaN NaN
83  SPEAKER  싼기타_비싼기타     1  417.750     3.480 NaN NaN  SPEAKER_01 NaN NaN
84  SPEAKER  싼기타_비싼기타     1  423.642     0.798 NaN NaN  SPEAKER_00 NaN NaN
85  SPEAKER  싼기타_비싼기타     1  424.745     3.548 NaN NaN  SPEAKER_00 NaN NaN
86  SPEAKER  싼기타_비싼기타     1  428.497     0.849 NaN NaN  SPEAKER_00 NaN NaN

[87 rows x 10 columns]

In [7]:
# start + duration을 end로 변환
df_rttm['end'] = df_rttm['start'] + df_rttm['duration']

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end
0,SPEAKER,싼기타_비싼기타,1,0.976,5.823,NaN,NaN,SPEAKER_01,NaN,NaN,6.799
1,SPEAKER,싼기타_비싼기타,1,7.394,3.973,NaN,NaN,SPEAKER_01,NaN,NaN,11.367
2,SPEAKER,싼기타_비싼기타,1,11.757,4.907,NaN,NaN,SPEAKER_01,NaN,NaN,16.664
3,SPEAKER,싼기타_비싼기타,1,17.224,10.645,NaN,NaN,SPEAKER_01,NaN,NaN,27.869
4,SPEAKER,싼기타_비싼기타,1,28.667,1.528,NaN,NaN,SPEAKER_01,NaN,NaN,30.195
...,...,...,...,...,...,...,...,...,...,...,...
82,SPEAKER,싼기타_비싼기타,1,414.474,2.971,NaN,NaN,SPEAKER_00,NaN,NaN,417.445
83,SPEAKER,싼기타_비싼기타,1,417.750,3.480,NaN,NaN,SPEAKER_01,NaN,NaN,421.230
84,SPEAKER,싼기타_비싼기타,1,423.642,0.798,NaN,NaN,SPEAKER_00,NaN,NaN,424.440
85,SPEAKER,싼기타_비싼기타,1,424.745,3.548,NaN,NaN,SPEAKER_00,NaN,NaN,428.293
86,SPEAKER,싼기타_비싼기타,1,428.497,0.849,NaN,NaN,SPEAKER_00,NaN,NaN,429.346

In [8]:
df_rttm["number"] = None	# number 열 만들고 None으로 초기화
df_rttm.at[0, "number"] = 0

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.976,5.823,NaN,NaN,SPEAKER_01,NaN,NaN,6.799,0
1,SPEAKER,싼기타_비싼기타,1,7.394,3.973,NaN,NaN,SPEAKER_01,NaN,NaN,11.367,None
2,SPEAKER,싼기타_비싼기타,1,11.757,4.907,NaN,NaN,SPEAKER_01,NaN,NaN,16.664,None
3,SPEAKER,싼기타_비싼기타,1,17.224,10.645,NaN,NaN,SPEAKER_01,NaN,NaN,27.869,None
4,SPEAKER,싼기타_비싼기타,1,28.667,1.528,NaN,NaN,SPEAKER_01,NaN,NaN,30.195,None
...,...,...,...,...,...,...,...,...,...,...,...,...
82,SPEAKER,싼기타_비싼기타,1,414.474,2.971,NaN,NaN,SPEAKER_00,NaN,NaN,417.445,None
83,SPEAKER,싼기타_비싼기타,1,417.750,3.480,NaN,NaN,SPEAKER_01,NaN,NaN,421.230,None
84,SPEAKER,싼기타_비싼기타,1,423.642,0.798,NaN,NaN,SPEAKER_00,NaN,NaN,424.440,None
85,SPEAKER,싼기타_비싼기타,1,424.745,3.548,NaN,NaN,SPEAKER_00,NaN,NaN,428.293,None
86,SPEAKER,싼기타_비싼기타,1,428.497,0.849,NaN,NaN,SPEAKER_00,NaN,NaN,429.346,None

In [9]:
for i in range(1, len(df_rttm)):
    if df_rttm.at[i, "speaker_id"] != df_rttm.at[i-1, "speaker_id"]:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"] + 1
    else:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"]

display(df_rttm.head(10))

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.976,5.823,NaN,NaN,SPEAKER_01,NaN,NaN,6.799,0
1,SPEAKER,싼기타_비싼기타,1,7.394,3.973,NaN,NaN,SPEAKER_01,NaN,NaN,11.367,0
2,SPEAKER,싼기타_비싼기타,1,11.757,4.907,NaN,NaN,SPEAKER_01,NaN,NaN,16.664,0
3,SPEAKER,싼기타_비싼기타,1,17.224,10.645,NaN,NaN,SPEAKER_01,NaN,NaN,27.869,0
4,SPEAKER,싼기타_비싼기타,1,28.667,1.528,NaN,NaN,SPEAKER_01,NaN,NaN,30.195,0
5,SPEAKER,싼기타_비싼기타,1,32.419,0.747,NaN,NaN,SPEAKER_00,NaN,NaN,33.166,1
6,SPEAKER,싼기타_비싼기타,1,33.557,3.531,NaN,NaN,SPEAKER_00,NaN,NaN,37.088,1
7,SPEAKER,싼기타_비싼기타,1,37.632,3.752,NaN,NaN,SPEAKER_00,NaN,NaN,41.384,1
8,SPEAKER,싼기타_비싼기타,1,41.621,1.104,NaN,NaN,SPEAKER_00,NaN,NaN,42.725,1
9,SPEAKER,싼기타_비싼기타,1,41.655,0.764,NaN,NaN,SPEAKER_01,NaN,NaN,42.419,2

In [10]:
df_rttm_grouped = df_rttm.groupby("number").agg(
    start=pd.NamedAgg(column='start', aggfunc='min'),
    end=pd.NamedAgg(column='end', aggfunc='max'),
    speaker_id=pd.NamedAgg(column='speaker_id', aggfunc='first')
)

display(df_rttm_grouped)

          start      end  speaker_id
number
0         0.976   30.195  SPEAKER_01
1        32.419   42.725  SPEAKER_00
2        41.655   44.015  SPEAKER_01
3        45.798   67.088  SPEAKER_00
4        67.224   82.776  SPEAKER_01
5        84.643  102.555  SPEAKER_00
6       103.489  117.513  SPEAKER_01
7       119.737  138.667  SPEAKER_00
8       139.346  168.956  SPEAKER_01
9       170.925  192.318  SPEAKER_00
10      192.317  193.675  SPEAKER_01
11      192.776  193.506  SPEAKER_00
12      193.879  216.578  SPEAKER_01
13      218.565  237.767  SPEAKER_00
14      238.107  238.650  SPEAKER_01
15      238.175  239.363  SPEAKER_00
16      239.856  240.637  SPEAKER_01
17      240.314  240.959  SPEAKER_00
18      241.044  251.316  SPEAKER_01
19      253.659  271.536  SPEAKER_00
20      272.148  304.541  SPEAKER_01
21      306.986  326.035  SPEAKER_00
22      326.358  335.459  SPEAKER_01
23      337.547  355.900  SPEAKER_00
24      356.256  363.981  SPEAKER_01
25      365.968  381.435  SPEAKER_00
26      382.165  383.727  SPEAKER_01
27      385.713  397.157  SPEAKER_00
28      397.615  399.092  SPEAKER_01
29      401.435  406.596  SPEAKER_00
30      407.411  408.311  SPEAKER_01
31      410.093  417.445  SPEAKER_00
32      417.750  421.230  SPEAKER_01
33      423.642  429.346  SPEAKER_00

In [11]:
df_rttm_grouped["duration"] = df_rttm_grouped["end"] - df_rttm_grouped["start"]
df_rttm_grouped = df_rttm_grouped.reset_index(drop=True)
display(df_rttm_grouped)

      start      end  speaker_id  duration
0     0.976   30.195  SPEAKER_01    29.219
1    32.419   42.725  SPEAKER_00    10.306
2    41.655   44.015  SPEAKER_01     2.360
3    45.798   67.088  SPEAKER_00    21.290
4    67.224   82.776  SPEAKER_01    15.552
5    84.643  102.555  SPEAKER_00    17.912
6   103.489  117.513  SPEAKER_01    14.024
7   119.737  138.667  SPEAKER_00    18.930
8   139.346  168.956  SPEAKER_01    29.610
9   170.925  192.318  SPEAKER_00    21.393
10  192.317  193.675  SPEAKER_01     1.358
11  192.776  193.506  SPEAKER_00     0.730
12  193.879  216.578  SPEAKER_01    22.699
13  218.565  237.767  SPEAKER_00    19.202
14  238.107  238.650  SPEAKER_01     0.543
15  238.175  239.363  SPEAKER_00     1.188
16  239.856  240.637  SPEAKER_01     0.781
17  240.314  240.959  SPEAKER_00     0.645
18  241.044  251.316  SPEAKER_01    10.272
19  253.659  271.536  SPEAKER_00    17.877
20  272.148  304.541  SPEAKER_01    32.393
21  306.986  326.035  SPEAKER_00    19.049
22  326.358  335.459  SPEAKER_01     9.101
23  337.547  355.900  SPEAKER_00    18.353
24  356.256  363.981  SPEAKER_01     7.725
25  365.968  381.435  SPEAKER_00    15.467
26  382.165  383.727  SPEAKER_01     1.562
27  385.713  397.157  SPEAKER_00    11.444
28  397.615  399.092  SPEAKER_01     1.477
29  401.435  406.596  SPEAKER_00     5.161
30  407.411  408.311  SPEAKER_01     0.900
31  410.093  417.445  SPEAKER_00     7.352
32  417.750  421.230  SPEAKER_01     3.480
33  423.642  429.346  SPEAKER_00     5.704

In [12]:
df_rttm_grouped.to_csv(
    "싼기타_비싼기타_rttm.csv",
    sep=',',
    index=False
)