In [ ]:
%pip install yfinance

In [1]:
import yfinance as yf

# Microsoft (MSFT)에 대한 Ticker 객체 생성
msft = yf.Ticker("MSFT")

# Ticker 객체에 대한 정보 출력 (.py에서 실행할 때는 print(msft.info)로 사용)
display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services that includes Bing and Copilot, Microsoft News and Edge, and third-party affiliates. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 8,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 6,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 399.95,
 'open': 400.135,
 'dayLow': 397.745,
 'dayHigh': 404.4,
 'regularMarketPreviousClose': 399.95,
 'regularMarketOpen': 400.135,
 'regularMarketDayLow': 397.745,
 'regularMarketDayHigh': 404.4,
 'dividendRate': 3.64,
 'dividendYield': 0.91,
 'exDividendDate': 1779321600,
 'payoutRatio': 0.21280001,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.108,
 'trailingPE': 24.99437,
 'forwardPE': 21.195595,
 'volume': 24516587,
 'regularMarketVolume': 24516587,
 'averageVolume': 34185491,
 'averageVolume10days': 30132970,
 'averageDailyVolume10Day': 30132970,
 'bid': 398.53,
 'ask': 399.44,
 'bidSize': 4,
 'askSize': 1,
 'marketCap': 2968566104064,
 'nonDilutedMarketCap': 2965870509245,
 'fiftyTwoWeekLow': 344.79,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 9.718569,
 'fiftyDayAverage': 426.2154,
 'twoHundredDayAverage': 482.6767,
 'trailingAnnualDividendRate': 3.48,
 'trailingAnnualDividendYield': 0.008701087,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2999686529024,
 'profitMargins': 0.39044,
 'floatShares': 7414787658,
 'sharesOutstanding': 7425629076,
 'sharesShort': 74347979,
 'sharesShortPriorMonth': 58407538,
 'sharesShortPreviousMonthDate': 1769731200,
 'dateShortInterest': 1772150400,
 'sharesPercentSharesOut': 0.01,
 'heldPercentInsiders': 0.00079,
 'heldPercentInstitutions': 0.75977,
 'shortRatio': 1.63,
 'shortPercentOfFloat': 0.01,
 'impliedSharesOutstanding': 7432377656,
 'bookValue': 52.615,
 'priceToBook': 7.5911813,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1767139200,
 'earningsQuarterlyGrowth': 0.595,
 'netIncomeToCommon': 119262003200,
 'trailingEps': 15.98,
 'forwardEps': 18.84401,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 9.82,
 'enterpriseToEbitda': 17.116,
 '52WeekChange': 0.029885054,
 'SandP52WeekChange': 0.18339145,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1771459200,
 'quoteType': 'EQUITY',
 'currentPrice': 399.41,
 'targetHighPrice': 730.0,
 'targetLowPrice': 392.0,
 'targetMeanPrice': 594.6217,
 'targetMedianPrice': 600.0,
 'recommendationMean': 1.2807,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 89461997568,
 'totalCashPerShare': 12.048,
 'ebitda': 175258992640,
 'totalDebt': 123278000128,
 'quickRatio': 1.239,
 'currentRatio': 1.386,
 'totalRevenue': 305453006848,
 'debtToEquity': 31.539,
 'revenuePerShare': 41.1,
 'returnOnAssets': 0.1486,
 'returnOnEquity': 0.34390998,
 'grossProfits': 209498996736,
 'freeCashflow': 53640626176,
 'operatingCashflow': 160506003456,
 'earningsGrowth': 0.598,
 'revenueGrowth': 0.167,
 'grossMargins': 0.68586,
 'ebitdaMargins': 0.57377,
 'operatingMargins': 0.47094002,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'postMarketTime': 1773791999,
 'regularMarketTime': 1773777602,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -0.135019,
 'regularMarketPrice': 399.41,
 'marketState': 'PREPRE',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': -0.17776006,
 'postMarketPrice': 398.7,
 'postMarketChange': -0.70999146,
 'regularMarketChange': -0.540009,
 'regularMarketDayRange': '397.745 - 404.4',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 34185491,
 'fiftyTwoWeekLowChange': 54.619995,
 'fiftyTwoWeekLowChangePercent': 0.15841524,
 'fiftyTwoWeekRange': '344.79 - 555.45',
 'fiftyTwoWeekHighChange': -156.04001,
 'fiftyTwoWeekHighChangePercent': -0.2809254,
 'fiftyTwoWeekChangePercent': 2.9885054,
 'dividendDate': 1773273600,
 'earningsTimestamp': 1769634000,
 'earningsTimestampStart': 1777492800,
 'earningsTimestampEnd': 1777492800,
 'earningsCallTimestampStart': 1769639400,
 'earningsCallTimestampEnd': 1769639400,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 15.98,
 'epsForward': 18.84401,
 'epsCurrentYear': 16.7292,
 'priceEpsCurrentYear': 23.875021,
 'fiftyDayAverageChange': -26.80539,
 'fiftyDayAverageChangePercent': -0.06289165,
 'twoHundredDayAverageChange': -83.26669,
 'twoHundredDayAverageChangePercent': -0.17251028,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.303}

In [2]:
hist = msft.history(period="5d") # 5일간의 주가 데이터를 가져옴
display(hist) # 데이터 출력

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-11 00:00:00-04:00,405.570007,409.010010,401.589996,404.880005,25512100,0.0,0.0
2026-03-12 00:00:00-04:00,404.630005,406.119995,401.709991,401.859985,27263900,0.0,0.0
2026-03-13 00:00:00-04:00,401.000000,404.799988,394.250000,395.549988,26848000,0.0,0.0
2026-03-16 00:00:00-04:00,398.070007,400.630005,394.790009,399.950012,27733700,0.0,0.0
2026-03-17 00:00:00-04:00,400.135010,404.399994,397.744995,399.410004,24516587,0.0,0.0

In [3]:
msft.recommendations # 추천 정보 출력

  period  strongBuy  buy  hold  sell  strongSell
0     0m         10   44     3     0           0
1    -1m         10   44     3     0           0
2    -2m         12   45     1     0           0
3    -3m         12   44     1     0           0